import {uid,clone,walletId,reconcileMonitor,order,eventId} from '../shared/engine.mjs';
import {demoEvents} from '../shared/demo.mjs';
export function registerMonitor(app,db,{getProject,saveJob,hasKey}){
 const key=id=>'monitor:'+id;
 const get=id=>{const row=db.prepare('SELECT data FROM monitor_states WHERE key=?').get(key(id));return row?JSON.parse(row.data):{projectId:id,enabled:false,status:'Paused',rows:[],observations:[],pending:[],activeJob:null,lastScan:null,nextScan:null,extraDemo:[],version:1};};
 const save=s=>db.prepare('INSERT INTO monitor_states(key,data) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data').run(key(s.projectId),JSON.stringify(s));
 const response=id=>{const s=get(id);return {...s,alerts:db.prepare('SELECT data,is_read FROM alerts WHERE project_id=? ORDER BY rowid DESC LIMIT 100').all(id).map(r=>({...JSON.parse(r.data),read:!!r.is_read}))};};
 const eligible=p=>p.wallets.filter(w=>w.kind==='wallet'&&((w.network==='ethereum'&&/^0x[0-9a-fA-F]{40}$/.test(w.address))||(p.demo&&w.network==='demo')));
 const fingerprint=p=>JSON.stringify({minGap:p.monitor.minGap,maxAge:p.monitor.maxAge,scope:p.monitor.scope,finality:p.monitor.finality});
 const apply=(s,p,w,events,coverage)=>{let row=s.rows.find(r=>r.id===w.id);if(!row){row={id:w.id,address:w.address,label:w.label,network:w.network,rule:fingerprint(p),version:s.version,seen:[],last:null,initialized:false,newCount:0,gap:null};s.rows.push(row);}if(row.rule!==fingerprint(p)){row.initialized=false;row.seen=[];row.last=null;row.rule=fingerprint(p);row.version++;}const qualifying=events.filter(e=>e.status==='success'&&BigInt(e.rawAmount)>0n&&(w.network==='demo'||e.confirmations>=64)&&(p.monitor.scope!=='outgoing'||walletId(e.network,e.from)===w.id)).sort(order);const oldLatest=row.last;const result=reconcileMonitor(row,qualifying,{...p.monitor,version:row.version});const oldSeen=new Set(row.seen);const newEvents=result.baseline?[]:qualifying.filter(e=>!oldSeen.has(e.id));row={...row,...result.state,label:w.label,previousScanLatest:oldLatest,latest:result.state.last,newCount:new Set(newEvents.map(e=>e.tx)).size,coverage,lastCheck:new Date().toISOString(),error:null};if(newEvents.length&&oldLatest?.timestamp&&newEvents[0].timestamp){row.previousTransaction=oldLatest;row.gap=(Date.parse(newEvents[0].timestamp)-Date.parse(oldLatest.timestamp))/1000;}s.rows=s.rows.map(r=>r.id===w.id?row:r);const observed=new Set(s.observations.map(e=>e.id));s.observations.push(...newEvents.filter(e=>!observed.has(e.id)));for(const alert of result.alerts){const id=`${p.id}:${w.id}:${row.version}:${alert.event.tx}`;db.prepare('INSERT OR IGNORE INTO alerts(id,project_id,data) VALUES(?,?,?)').run(id,p.id,JSON.stringify({...alert,id,label:w.label,walletId:w.id,rule:p.monitor}));}}
 const request=(id,enabled)=>{const p=getProject(id),s=get(id);if(!p.demo&&!hasKey())throw Error('Configure an Etherscan API key before scanning live wallets.');if(enabled!==undefined)s.enabled=enabled;const wallets=eligible(p);if(!wallets.length)throw Error('No eligible Ethereum wallets to monitor. Solana, unconfigured networks, and manual placeholders are excluded.');s.error=null;s.budgetRemaining=Math.max(1,Math.min(100,Number(p.monitor.budget)||20));if(!s.pending.length&&!s.activeJob)s.pending=wallets.map(w=>w.id);s.status='Running';s.nextScan=null;if(s.activeJob){const j=JSON.parse(db.prepare('SELECT data FROM jobs WHERE id=?').get(s.activeJob).data);if(j.status!=='complete'){j.status='queued';j.budget=j.used+s.budgetRemaining;j.retryAt=0;j.error=null;saveJob(j);}}save(s);return response(id);};
 app.get('/api/monitor/:id',req=>{getProject(req.params.id);return response(req.params.id);});
 app.post('/api/monitor/:id/start',req=>request(req.params.id,true));
 app.post('/api/monitor/:id/scan',req=>request(req.params.id));
 app.post('/api/monitor/:id/pause',req=>{const s=get(req.params.id);s.enabled=false;s.status='Paused';s.nextScan=null;if(s.activeJob){const j=JSON.parse(db.prepare('SELECT data FROM jobs WHERE id=?').get(s.activeJob).data);j.status='paused';saveJob(j);}save(s);return response(req.params.id);});
 app.post('/api/monitor/:id/read',req=>{db.prepare('UPDATE alerts SET is_read=1 WHERE id=? AND project_id=?').run(req.body.id,req.params.id);return {ok:true};});
 app.post('/api/monitor/:id/stage',req=>({events:get(req.params.id).observations}));
 app.post('/api/monitor/:id/demo-burst',req=>{const p=getProject(req.params.id);if(!p.demo)throw Error('Simulation is available only for fictional projects.');const s=get(p.id);if(!s.rows.some(r=>r.initialized))throw Error('Use Check now first to establish fictional baselines.');const source=demoEvents()[0];const time=Date.now();const block=2000+s.extraDemo.length;s.extraDemo.push(...[0,1,2].map(i=>{const e={...clone(source),tx:'fictional-reactivation-'+uid(),timestamp:new Date(time+i).toISOString(),block:block+i,rawAmount:'1000000000000000000'};e.id=eventId(e);return e;}));save(s);return request(p.id);});
 let busy=false;const monitorTimer=setInterval(async()=>{if(busy)return;busy=true;try{for(const record of db.prepare("SELECT data FROM monitor_states WHERE key LIKE 'monitor:%'").all()){let s=JSON.parse(record.data);let p;try{p=getProject(s.projectId);}catch{continue;}if(s.enabled&&s.nextScan&&Date.parse(s.nextScan)<=Date.now()){request(p.id);s=get(p.id);}if(!['Running','Catching up','Throttled'].includes(s.status))continue;if(p.demo){db.exec('BEGIN IMMEDIATE');try{for(const id of s.pending){const w=p.wallets.find(w=>w.id===id);if(w)apply(s,p,w,[...demoEvents(),...s.extraDemo].filter(e=>walletId(e.network,e.from)===id||walletId(e.network,e.to)===id),'Fictional history');}s.pending=[];s.status=s.enabled?'Waiting':'Paused';s.lastScan=new Date().toISOString();s.nextScan=s.enabled?new Date(Date.now()+p.monitor.interval*1000).toISOString():null;save(s);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}continue;}
 if(s.activeJob){const j=JSON.parse(db.prepare('SELECT data FROM jobs WHERE id=?').get(s.activeJob).data);if(j.status==='complete'){const w=p.wallets.find(w=>w.id===s.pending[0]);db.exec('BEGIN IMMEDIATE');try{if(w)apply(s,p,w,j.events,j.coverage+'; other event classes unknown');s.budgetRemaining-=j.used-(s.jobInitialUsed||0);s.pending.shift();s.activeJob=null;save(s);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}else if(['error','budget reached','paused'].includes(j.status)){s.status=j.status==='error'?'Error':'Catching up';s.error=j.error||'Request budget reached. Check now or the next scheduled scan resumes the saved cursor. Checkpoint has not advanced.';s.nextScan=s.enabled?new Date(Date.now()+p.monitor.interval*1000).toISOString():null;save(s);continue;}else if(j.status==='throttled'){s.status='Throttled';s.error=j.error;save(s);continue;}else continue;}
 if(!s.pending.length){s.lastScan=new Date().toISOString();s.status=s.enabled?'Waiting':'Paused';s.nextScan=s.enabled?new Date(Date.now()+p.monitor.interval*1000).toISOString():null;save(s);continue;}if(s.budgetRemaining<=0){s.status='Catching up';s.error='Scan request budget reached. Unchecked wallets remain queued.';s.nextScan=s.enabled?new Date(Date.now()+p.monitor.interval*1000).toISOString():null;save(s);continue;}const w=p.wallets.find(w=>w.id===s.pending[0]);if(!w){s.pending.shift();save(s);continue;}const row=s.rows.find(r=>r.id===w.id);const j={id:uid(),projectId:p.id,address:w.address.toLowerCase(),network:'ethereum',startblock:row?.last?.block?Math.max(0,Number(row.last.block)-12):0,endblock:99999999,page:1,budget:s.budgetRemaining,used:0,events:[],raw:[],status:'queued',coverage:'partial',createdAt:new Date().toISOString(),retryAt:0,purpose:'monitor'};saveJob(j);s.activeJob=j.id;s.jobInitialUsed=0;save(s);
 }}catch(e){console.error('Monitor processing failed:',e.message);}finally{busy=false;}},1500).unref();
 app.addHook('onClose',async()=>clearInterval(monitorTimer));
 // Paused restores and restarts are explicit, retaining baselines and pending pages.
 for(const r of db.prepare("SELECT data FROM monitor_states WHERE key LIKE 'monitor:%'").all()){const s=JSON.parse(r.data);s.enabled=false;s.status='Paused';s.nextScan=null;save(s);}
}
