import {newProject, eventId, walletId, parseAmount} from './engine.mjs';
export function demoEvents(){const rows=[
 ['01','early-funder','atlas-wallet','100','ETH','native',18,0],
 ['02','atlas-wallet','relay-alpha','40','ETH','native',18,1],
 ['03','relay-alpha','relay-beta','40','ETH','native',18,2],
 ['04','relay-beta','relay-gamma','40','ETH','native',18,3],
 ['05','relay-gamma','vault-wallet','40','ETH','native',18,4],
 ['06','atlas-wallet','swap-router','20','ETH','native',18,5],
 ['06','swap-router','eth-usdc-pool','20','ETH','native',18,6],
 ['06','eth-usdc-pool','usdc-dai-pool','60000','USDC','demo-usdc',6,7],
 ['06','usdc-dai-pool','destination-wallet','60000','DAI','demo-dai',18,8],
 ['07','atlas-wallet','loop-beta','10','ETH','native',18,9],
 ['08','loop-beta','loop-gamma','10','ETH','native',18,10],
 ['09','loop-gamma','atlas-wallet','10','ETH','native',18,11],
 ['10','atlas-wallet','exit-wallet','10','ETH','native',18,12]
 ];return rows.map(([tx,from,to,amount,symbol,assetId,decimals,i])=>{const e={network:'demo',tx:`fictional-tx-${tx}`,eventIndex:tx==='06'?`log:${i-5}`:'transfer:0',ordinal:i,block:1000+Number(tx),transactionIndex:0,from:`demo:${from}`,to:`demo:${to}`,rawAmount:parseAmount(amount,decimals),symbol,assetId,decimals,timestamp:new Date(Date.UTC(2026,8,tx==='06'?6:1+i,10,20)).toISOString(),verification:'unverified',status:'success',finality:'fictional',sources:[{provider:'Fictional demonstration',retrievedAt:'2026-09-19T00:00:00Z',reference:'Synthetic fixture; not on-chain evidence'}],notes:'',feeRaw:'0',feeNote:'Fees excluded from this simplified fictional fixture.'};e.id=eventId(e);return e;});}
export function demoProject(){const p=newProject('Atlas · funding investigation');p.demo=true;p.notes='# Atlas funding investigation\n\n## Working observations\n- Follow the earliest observed funding into **Atlas wallet**.\n- A 40 ETH branch passes through three relay wallets to the vault.\n- A separate 20 ETH route swaps through two pools into 60,000 DAI.\n- The 10 ETH loop returns to Atlas before a later 10 ETH exit.\n\n## Open questions\n- Review the relay subsystem and its boundary transfers.\n- The NFT marker is a hypothesis, not a payment or ownership link.\n\n**Fictional dataset.** No addresses or transactions here represent real activity. Opening pool reserves are outside this fixture; fees are omitted. No ownership conclusions are implied.';
const specs=[['early-funder','Early funder','wallet',20,230],['atlas-wallet','Atlas wallet','wallet',270,230],['relay-alpha','Relay α','wallet',530,10],['relay-beta','Relay β','wallet',770,10],['relay-gamma','Relay γ','wallet',1010,10],['vault-wallet','Vault wallet','wallet',1260,30],['swap-router','Swap router','router',530,250],['eth-usdc-pool','ETH / USDC pool','pool',770,250],['usdc-dai-pool','USDC / DAI pool','pool',1010,250],['destination-wallet','Swap destination','wallet',1260,250],['loop-beta','Loop β','wallet',530,490],['loop-gamma','Loop γ','wallet',770,490],['exit-wallet','Later exit','wallet',1010,490],['nft-marker','Possible NFT relationship','marker',1260,490]];
p.wallets=specs.map(([a,label,kind,x,y])=>{const address=`demo:${a}`,id=walletId('demo',address);p.instances[0].positions[id]={x,y};return {id,network:'demo',address,label,kind,notes:kind==='marker'?'Hypothesis: review whether an NFT movement is related. No payment or ownership relationship is established.':'',tags:a==='atlas-wallet'?['focus']:[],coverage:'fictional'};});p.events=demoEvents();p.staging=demoEvents();const group={id:'demo-relay-subsystem',name:'Relay subsystem',members:['relay-alpha','relay-beta','relay-gamma'].map(a=>walletId('demo',`demo:${a}`)),notes:'Three sequential relay wallets. This pattern does not establish common ownership or intent.'};p.groups=[group];p.instances[0].collapsed=[group.id];p.instances[0].positions[group.id]={x:700,y:15};p.history=[{id:'initial-demo',at:new Date().toISOString(),text:'Opened fictional demonstration · 13 transfer events / 10 transactions'}];return p;}
