export const uid = () => crypto.randomUUID();
export const clone = x => structuredClone(x);
export function canonical(network,address) {return network==='ethereum'?address.toLowerCase():address;}
export function walletId(network,address){return `${network}:${canonical(network,address)}`;}
export function eventId(e){return `${e.network}:${e.tx}:${e.eventIndex}`;}
export function formatAmount(raw,decimals=18){const neg=String(raw).startsWith('-');const s=String(raw).replace('-','').padStart(decimals+1,'0');return (neg?'-':'')+(decimals?`${s.slice(0,-decimals)}.${s.slice(-decimals)}`.replace(/\.?0+$/,''):s);}
export function parseAmount(value,decimals=18){if(!/^\d+(\.\d+)?$/.test(value))throw Error('Enter a positive decimal amount.');let [a,b='']=value.split('.');if(b.length>decimals)throw Error(`This asset supports ${decimals} decimal places.`);return BigInt(a+b.padEnd(decimals,'0')).toString();}
export function order(a,b){return Number(a.block??0)-Number(b.block??0)||Number(a.transactionIndex??0)-Number(b.transactionIndex??0)||Number(a.ordinal??0)-Number(b.ordinal??0)||String(a.id).localeCompare(String(b.id));}
export function validateEvent(e){
 if(!e || typeof e!=='object')throw Error('Each event must be an object.');
 for(const k of ['network','tx','eventIndex','from','to','assetId','symbol','rawAmount'])if(typeof e[k]!=='string'||!e[k]||e[k].length>2000)throw Error(`Missing or invalid ${k}.`);
 if(!/^\d+$/.test(e.rawAmount)||!Number.isInteger(e.decimals)||e.decimals<0||e.decimals>36)throw Error('Amounts must be exact unsigned integer strings, with decimals from 0 to 36.');
 if(e.timestamp!==null && (!e.timestamp||!Number.isFinite(Date.parse(e.timestamp))))throw Error('Use an ISO timestamp, or null when unknown.');
 if(!['ethereum','solana','robinhood','demo'].includes(e.network))throw Error('Unknown network.');
 if(e.network==='ethereum'&&((!/^0x[0-9a-fA-F]{40}$/.test(e.from)&&!(e.hypothesis&&e.from.startsWith('unknown:')))||(!/^0x[0-9a-fA-F]{40}$/.test(e.to)&&!(e.hypothesis&&e.to.startsWith('unknown:')))))throw Error('Ethereum endpoints must be 0x addresses with 40 hexadecimal characters.');
 return {...e,from:canonical(e.network,e.from),to:canonical(e.network,e.to),id:eventId(e),status:e.status==='failed'?'failed':'success',verification:'unverified',sources:Array.isArray(e.sources)?e.sources:[],notes:typeof e.notes==='string'?e.notes:''};
}
const factual = ['network','tx','eventIndex','from','to','assetId','rawAmount','decimals','status','timestamp','block','blockHash','transactionIndex','ordinal'];
export function importStatus(project,e){const old=project.events.find(x=>x.id===e.id);if(!old)return 'New';if(factual.some(k=>old[k]!==e[k]))return 'Conflict';if((e.sources||[]).some(s=>!(old.sources||[]).some(t=>JSON.stringify(s)===JSON.stringify(t))))return 'Enrichment';return 'Already imported';}
export function importEvents(project,events){const p=clone(project);let added=0,enriched=0,conflicts=0;for(const e of events){const status=importStatus(p,e);if(status==='Conflict'){p.conflicts.push({id:uid(),existing:e.id,incoming:e,at:new Date().toISOString()});conflicts++;continue;}if(status==='Already imported')continue;if(status==='Enrichment'){const old=p.events.find(x=>x.id===e.id);old.sources=[...old.sources,...e.sources.filter(s=>!old.sources.some(t=>JSON.stringify(t)===JSON.stringify(s)))];enriched++;continue;}p.events.push(e);added++;for(const address of [e.from,e.to]){const id=walletId(e.network,address);if(!p.wallets.some(w=>w.id===id))p.wallets.push({id,network:e.network,address,label:address.length>18?address.slice(0,7)+'…'+address.slice(-5):address,kind:'wallet',notes:'',coverage:'unknown',tags:[]});}}
return {project:p,added,enriched,conflicts};}
export function totals(events,members){const set=new Set(members);const out={};for(const e of events){if(e.status==='failed'||e.hypothesis)continue;const from=set.has(walletId(e.network,e.from)),to=set.has(walletId(e.network,e.to));if(!from&&!to)continue;const key=`${e.network}:${e.assetId}`;out[key]??={symbol:e.symbol,assetId:e.assetId,network:e.network,decimals:e.decimals,inflow:0n,outflow:0n,internal:0n};const n=BigInt(e.rawAmount);if(from&&to)out[key].internal+=n;else if(to)out[key].inflow+=n;else out[key].outflow+=n;}
return Object.values(out).map(t=>({...t,inflow:formatAmount(t.inflow.toString(),t.decimals),outflow:formatAmount(t.outflow.toString(),t.decimals),internal:formatAmount(t.internal.toString(),t.decimals),net:formatAmount((t.inflow-t.outflow).toString(),t.decimals)}));}
export function trace(events,start,{direction='forward',maxDepth=6,limit=250,assetId='',boundary=null,dust='0',stopServices=[],firstFunding=false}={}){const sorted=[...events].filter(e=>e.status!=='failed'&&!e.hypothesis&&(!assetId||e.assetId===assetId)&&BigInt(e.rawAmount)>BigInt(dust)).sort(order);const result=new Set(),states=new Set(),queue=[{wallet:start,index:boundary??(direction==='forward'?-1:sorted.length),depth:0}];let truncated=false;while(queue.length){const s=queue.shift();const key=`${s.wallet}:${s.index}:${direction}`;if(states.has(key))continue;states.add(key);if(s.depth>=maxDepth){truncated=true;continue;}if(s.depth>0&&stopServices.includes(s.wallet))continue;let eligible=sorted.map((e,i)=>({e,i})).filter(({e,i})=>direction==='forward'?i>s.index&&walletId(e.network,e.from)===s.wallet:i<s.index&&walletId(e.network,e.to)===s.wallet);if(firstFunding&&direction==='backward')eligible=eligible.slice(0,1);for(const {e,i} of eligible){result.add(e.id);if(result.size>=limit){truncated=true;queue.length=0;break;}queue.push({wallet:walletId(e.network,direction==='forward'?e.to:e.from),index:i,depth:s.depth+1});}}return {ids:[...result],states:states.size,truncated,coverage:'Accepted evidence only; history may be incomplete.'};}
export function newProject(name='Untitled investigation'){return {id:uid(),name,createdAt:new Date().toISOString(),notes:'',wallets:[],events:[],groups:[],conflicts:[],staging:[],history:[],instances:[{id:uid(),name:'Main investigation',positions:{},collapsed:[],mode:'Funds',layout:'Freeform',timeline:100,leftWidth:30,graphHeight:68,notesTab:'Project Notes'}],activeInstance:0,archived:false,monitor:{enabled:false,interval:300,budget:20,minGap:604800,maxAge:3600,scope:'outgoing',finality:'confirmed'},presets:[]};}
export function validateProject(p){if(!p||typeof p.name!=='string'||!Array.isArray(p.events)||!Array.isArray(p.wallets)||!Array.isArray(p.instances)||!p.instances.length)throw Error('Invalid project backup.');if(p.events.length>20000||p.wallets.length>10000)throw Error('Backup exceeds this edition’s limits.');for(const e of p.events){validateEvent(e);if(e.id!==eventId(e))throw Error('Event identity does not match its source identifiers.');}if(new Set(p.events.map(e=>e.id)).size!==p.events.length)throw Error('Backup contains duplicate event identities.');for(const k of ['groups','conflicts','staging','history','presets'])if(!Array.isArray(p[k]))throw Error('Backup is missing '+k+'.');if(!Number.isInteger(p.activeInstance)||p.activeInstance<0||p.activeInstance>=p.instances.length)throw Error('Invalid active view.');for(const v of p.instances)if(!v.id||typeof v.name!=='string'||!v.positions||typeof v.positions!=='object'||!Array.isArray(v.collapsed))throw Error('Invalid view layout.');const walletIds=new Set();for(const w of p.wallets){if(typeof w.address!=='string'||typeof w.network!=='string'||w.id!==walletId(w.network,w.address)||typeof w.label!=='string')throw Error('Invalid wallet identity.');if(walletIds.has(w.id))throw Error('Duplicate wallet identity.');walletIds.add(w.id);}for(const e of p.events)if(!walletIds.has(walletId(e.network,e.from))||!walletIds.has(walletId(e.network,e.to)))throw Error('Event endpoints must reference project wallets.');const groupIds=new Set(p.groups.map(g=>g.id));for(const g of p.groups){if(!Array.isArray(g.members)||g.members.some(id=>!walletIds.has(id)&&!groupIds.has(id)))throw Error('Invalid group member.');const visit=(id,path)=>{if(path.has(id))throw Error('Nested groups must not contain cycles.');const child=p.groups.find(x=>x.id===id);if(child)for(const member of child.members)visit(member,new Set([...path,id]));};visit(g.id,new Set());}return p;}
export function reconcileMonitor(previous,events,rule,now=Date.now()){const sorted=[...events].sort(order);const state=clone(previous||{initialized:false,seen:[],last:null});const seen=new Set(state.seen);const alerts=[];if(!state.initialized){state.initialized=true;state.seen=sorted.map(e=>e.id);state.last=sorted.at(-1)||null;return {state,alerts,baseline:true};}for(const e of sorted){if(seen.has(e.id))continue;seen.add(e.id);if(state.last&&order(e,state.last)<=0)continue;const gap=state.last?.timestamp&&e.timestamp?(Date.parse(e.timestamp)-Date.parse(state.last.timestamp))/1000:null;const age=e.timestamp?(now-Date.parse(e.timestamp))/1000:null;if(gap!==null&&age!==null&&gap>=rule.minGap&&age>=0&&age<=rule.maxAge)alerts.push({id:`${rule.version||1}:${e.network}:${e.tx}`,event:e,previous:state.last,gap,detectedAt:new Date(now).toISOString()});state.last=e;}state.seen=[...seen];return {state,alerts,baseline:false};}
export function groupMembers(project,groupId,seen=new Set()) {if(seen.has(groupId))return [];seen.add(groupId);const g=project.groups.find(g=>g.id===groupId);if(!g)return [groupId];return [...new Set(g.members.flatMap(id=>groupMembers(project,id,seen)))];}
